root:
    path: /
    controller: Puzzle\Controller\RootController::front
    methods: GET
components:
    path: /api/components
    controller: Puzzle\Controller\Api\ComponentController::index
    methods: GET
components.render:
    path: /api/components/{id}/render
    controller: Puzzle\Controller\Api\ComponentController::output
    methods: GET
api.pages.fetch:
    path: /api/pages/{uuid}
    controller: Puzzle\Controller\Api\PageController::fetch
    methods: GET
components.update:
    path: /api/components/{id}/update
    controller: Puzzle\Controller\Api\ComponentController::update
    methods: PUT
components.undo:
    path: /api/components/{id}/undo
    controller: Puzzle\Controller\Api\ComponentController::undo
    methods: PUT
admin.pages:
    path: /admin/pages
    controller: Puzzle\Controller\Admin\PageController::index
    methods: [GET,HEAD]
admin.pages.create:
    path: /admin/pages/create
    controller: Puzzle\Controller\Admin\PageController::create
    methods: GET
admin.pages.store:
    path: /admin/pages
    controller: Puzzle\Controller\Admin\PageController::store
    methods: [POST]
