#!/usr/bin/env php
<?php

use Puzzle\Bootstrap;
use Puzzle\Console\Command\StorageLinkCommand;
use Puzzle\Console\Command\TestCommand;
use Symfony\Component\Console\Application;

require 'autoload.php';

$container = Bootstrap::boot();

$application = new Application('Puzzle');

$application->add(new TestCommand());
$application->add(new StorageLinkCommand());

$application->run();
