container: false
template: templates/heading.html.twig
css:
    variables:
        text: 'font-medium'
        h1: 'text-3xl mb-6'
        h2: 'text-2xl mb-4'
        h3: 'text-xl mb-4'
        h4: 'text-lg mb-3'
        h5: 'text-normal mb-2'
        h6: 'text-sm mb-2'
fields:
    text:
        label: Title
        type: input_text
        default_value: 'Title level 2'
    heading:
        label: Heading
        type: dropdown
        options:
            h1: H1
            h2: H2
            h3: H3
            h4: H4
            h5: H5
            h6: H6
        default_value: h2
