name: PHP CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    php-tests:
        name: Run PHPUnit and PHPCS
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Set up PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.3'
                    extensions: mbstring, pdo, dom

            -   name: Install dependencies
                run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

            -   name: Run PHPUnit
                run: vendor/bin/phpunit

            -   name: Run PHPCS
                run: vendor/bin/phpcs --standard=phpcs.xml
    eslint:
        name: Run ESLint
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Setup Node.js
                uses: actions/setup-node@v3
                with:
                    node-version: 22  # Change to your preferred Node.js version

            -   name: Install Dependencies
                run: npm install

            -   name: Run ESLint
                run: npm run lint
